calibrate:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: slide
          domain: cover
touchgo:
  description: "Enable or disable Touch Go of the Slide."
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: slide
          domain: cover
    touchgo:
      required: true
      selector:
        boolean:
